receivers:
  prometheus:
    config:
      global:
        scrape_interval: 60s
        scrape_timeout: 60s
      scrape_configs:
        - job_name: "yace-exporter"
          static_configs:
            - targets: [localhost:5000]

exporters:
  prometheusremotewrite:
    endpoint: <PROMETHEUS_ENDPOINT>
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
