apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
  jobs:
    - type: AWS/EC2
      regions:
        - ap-northeast-1
      period: 300
      length: 300
      metrics:
        - name: CPUCreditUsage
          statistics: [Average]
        - name: CPUCreditBalance
          statistics: [Average]

    - type: AWS/RDS
      regions:
        - ap-northeast-1
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics: [Maximum]
        - name: DatabaseConnections
          statistics: [Sum]
        - name: FreeableMemory
          statistics: [Average]
        - name: FreeStorageSpace
          statistics: [Average]
        - name: ReadThroughput
          statistics: [Average]
        - name: WriteThroughput
          statistics: [Average]
        - name: ReadIOPS
          statistics: [Average]
        - name: WriteIOPS
          statistics: [Average]
        - name: ReadLatency
          statistics: [Maximum]
        - name: WriteLatency
          statistics: [Maximum]

    - type: AWS/FSx
      regions:
        - ap-northeast-1
      period: 300
      length: 300
      metrics:
        - name: FreeStorageCapacity
          statistics: [Average]
        - name: CPUUtilization
          statistics: [Average]
        - name: MemoryUtilization
          statistics: [Average]

    - type: AWS/Backup
      regions:
        - ap-northeast-1
      period: 300
      length: 300
      metrics:
        - name: NumberOfBackupJobsFailed
          statistics: [Average]
        - name: NumberOfBackupJobsRunning
          statistics: [Average]
        - name: NumberOfBackupJobsCompleted
          statistics: [Average]
